services:
  dev-db:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pb_dev
    networks:
      - personal-budgeting

networks:
  personal-budgeting: